# Generated by Django 4.2 on 2023-06-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_anime', models.CharField(max_length=100)),
                ('nomes_alternativos', models.CharField(max_length=150)),
                ('tags_genero', models.CharField(max_length=200)),
                ('anime_sinopse', models.TextField()),
                ('imagem_anime', models.ImageField(blank=True, upload_to='Imagens/%d/%m/%Y/')),
                ('links', models.URLField(max_length=255)),
                ('lancamentos', models.BooleanField(default=False)),
                ('publicada', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
