# Generated by Django 4.2 on 2023-07-08 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animes',
            name='data_anime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
