# Generated by Django 4.2 on 2023-07-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_alter_animes_tags_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='tags_genero',
            field=models.CharField(max_length=200),
        ),
    ]
