# Generated by Django 4.2 on 2023-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_alter_animes_tags_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
